version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - db    

  db:
    image: mysql:5.7.16
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/1.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password      

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app